name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  jekyll:
    name: Build and deploy Jekyll Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: SebasWild/jekyll-build-action@445d650279c45fd66c59ddd38620ddb30fceaedf

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      environment: gh-jekyll
      env:
        SSH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEAugcBiz84c25NELCX7XQ6wzlPIT7xjYk31EmraZ4PjXKLZCdt
rpdRYNZaZHPL2e7cgW4n1R9iTNHr0wtHBYVSNvOYFF4VGMvixWCqPK4oXr8L0RS9
yRmrlqzLTLT1D7qXjhwedbF6/uy8qvIoNobGIaJfXyIzhwUbjh7YLqVyb6ZjaPN/
FbdLg8cwHW1KJjQZkgaxHqyBQlGmsJ7K1jt7jJfmdcKRItvhGxpJq5hsEA4iNmpF
JYjRT+Z+zFDW1CQaItPaEp0xmMGLKorXkozEeIYupKVwcskVsDGDLI4Cfbb8QCzv
B5kV+fBJ0BccWZV+Zg+Jjx9bSqQbp07f2jkprcqQfQMU5o1Ax86A992CzjVokRQv
f0DSQ8LDlKKgedFwlJrh72T5f86MhcuqkWpL52pBgvUMuNZfdsBZw5u6NRjnRo9B
+B4ZBG3AQCWdDu6rjxFff/09zJfIVA9tICRvnNzhvTeSykhRB97BcB3zCPzLxTew
OGuDhxM6UARHLDTwLJzwzG7EtB8L6KCSjS8SdDIUC5qOZlO34Dlotj/kVszQiW3I
sXyVM4mGjdniz18Y51jOyrhr3Q1slQZ6GwseCpUPYWUUrcAbFyTO7khLKlAmUU1H
/B/YfkCE6KJSLuLdyhCLgaWPcG6INwMkRlgg9jTEL775F50oOZzgPTs9DlkCAwEA
AQKCAgBqaPeJH3C7Fq0ejuVY/tNeOLn62nZx77vvwvQ6Rh+/WXZCpAspg4UZT4QF
UfeZgfjAULKYRouERdAPuLO3hLuyk0S64dZPiND+9nxqmXSePcoUnziwf+6XEeB4
0Eod5S4sLAmAaTVh/Sku37YA+rb7JlZHpNi0s0c/1IT0qc777sGOlzpqwZ6AksAD
FTEFCWhXD1zhnuuRdANVpH+CbCQQGBPL6K/8sKnjRvY9IcMuq+cGGWPURJ72hXKi
jNtWHhCVO3nSi/iC2LMycpk9SyhXiOnFZJ0eC8hMMQZHxjPGlZVVYF6aigb4IWsX
jSC6XbkfyGN3awhdeeIXohaKTYh41zeFul/L2G78DnkO50bIU6VBx/KXXFjCvSCp
xP1RxGcRSXfuAWTKt5En/nHWFg0Cvf60UV7Xf3XS0g9eghUb7mPPsUwNc0r5JLyx
EdmbsM8rVIHtoaceDev5mxMcIEdjsi9lrecBef9y1Tfbp/nMAj9I2ncWeBnGORXy
srdLiAAbM/gGl4yATx/AeT/rGcyCOydWzfxn9n6Zc8a6KKb15GEdcEgW7vqPbfzX
QM09HyuZoHrwNxQqrWoHs62yhMRlO6udq/9wwG4++/HkXLcUlHel7O2M9ePpyM4z
WFd/FledvfubUEGkjNgGdjYgkDkr/OHwMeFVtWvmbkLBpZkoAQKCAQEA41XgbrNK
cEVG4UffcUbN9Bh+QaIvfM3EdIEGD0/Iz2OAgqN7qBPXM+/zO3YBY1dtOB7afmTA
8lZ12iumxtMaVqBZ7OGeT/v0AYAvPVwz2pYjMo7otY8wkoMOh0X9I1dtIG8biIKD
PYOw73hAap0pa37q8cRYlYI5WmlNCRgTsFnDipCgCHDZWYyCX0zh7aOkrvL8+Elk
U9+JBufp79aciDb5SwZ+mdDxGB4NBokA0dlieXMEhjUWZYD1HUjaq9149/nS8axC
266DegWN0vx8TEJIgmdTfa1YgxCYdco53MVwq4+oqzT13Ujef8hYCCf0L7NIB3C4
HTUyUabVC3SZ6QKCAQEA0XvAn3z99JdHsOAsokex1+RN87zYWZiNlCoJBOYdfjii
kXYf3tu+C0ndTQ0yjfsxBk/EbxhyfnCtXpJNOYINE8m5PxYrs4FkAo3uEA+Yd4v/
IUO882ivG2HYxLTMxhG2f+VNdikxgsPbAAoG8nOQtSuPsKufRJOB0fkHusK4X1vu
/6t96WuetRuldLtQZJApmcpKQR0yKfmqcDwWLYTxJi1hsKbVhzH4FjNBzDfXNTui
glh92eaQ42+T6GQECvbbsUqz/B0okkQnbbQRlLJRSFB1zenE6KLmf/6qKS3f83mQ
bJF49xirotyo8RTBXMyQdKLmDUrqizE6B/cx75Ka8QKCAQEAnLpR1j/pK+m26g1g
8Hl997EDKkCkOIirzh49jUTWDpRsvqPy1neHQBlHOVErt89ITw6GV+kiVHBjI5xA
iIZ1fA9kr7kEKeRr3rT+3HC6lxI3Bd4cdT9Yn0mXNI9962WUqG2xL7W6wSgPTak7
z8S2D5Qaab+RytFStRAvuftNZ6Ea/GakzezvC5uhLg6VG/5bxPlkidAfSOutToOI
dn8gv5AW4jCCC41PCe99z2mYlRQnnc876UKkRCpZ0mytxRsVEPC9CzxVg5qWrgMy
Oak0EGcKEk0l9FkT0pgYY+ydY6UC/mQ2RoJmlr5sFvCKMGVLJa+WEvsVE53fKQe5
jQJAMQKCAQBDX7/mC7dJ8VXXZ2Izl0d1njIMEFKtDkmKu7JG5xPZQrHWgt1hOd93
lfwdCf+WdpGf7AvLh1tbmzXHUtqPgmpeUOTJi4Hmq9jUkX1doQZyfI5Dzpt41dRr
xB6JtXSex5egrskpFbqcyg0niBIP7GdAPZBrS+dfkOmR9Lwtru7JjLHjfO50Im7a
5NdkIdKLZWpb0hnrs04s/eV5T3n6jeVZWAMxY5cNcl7OFRI2ckc/Eb0Emx1u9Z7n
5zz04yYBuL+T1+jnTyF7WXws5ls5LdjCn04kOelgwPPNesSTlfOPRSvUHz1+i2q4
aKvVTc2a4Rgcyz+eStgAiIaXhUOEP+yhAoIBAQCRfEEMlexbZanP5DNyfHPKhNXU
Rcra+3zoD6DS1/ja1sLhO8qm/dDfHeIUX+W1v9Lb4lFHg+RJ5obl/Inenypd6W03
PB7sztqGrUpE30vXWszSJWvM67iWddZp2g4KKtqMfIfRQt2p5DgUnn/33WlBHmpT
lLrZhSIMQaQ2X7HelsA4ZgETgktAMBt1SWo+BV9JyJqRtCu+Js4uTntxZ3iLmhg4
I2FBfMIFKD+0T8UOy0gY9AMiNE2QrtwYRpm9WV1TBzmY2Tytr91kavsoQVXtyVFy
oWGx+CieyLIWfgHB3HniQ1K/VV2HrG10CnCKAwfJoKJcCCG+E4TFeU39iZjs
-----END RSA PRIVATE KEY-----"
        ARGS: "-rzv --delete --delete-excluded --chmod=g+rwx"
        SOURCE: "./_site/"
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        TARGET: ${{ secrets.DEPLOY_TARGET }}
#
    # - name: Purge Cloudflare Cache
    #   uses: jakejarvis/cloudflare-purge-action@v0.3.0
    #   env:
    #     CLOUDFLARE_ZONE: $
    #     CLOUDFLARE_TOKEN: $